### ISSUE TITLE
Failed to create log group in Cloudwatch

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [rjocoleman/syslog-cloudwatch-bridge#6]
Assuming this is an issue specific to us-gov region but not sure as have not tested this outside gov region. Once I manually created the log group everything worked as expected.

docker-compose.yml
```
version: "3.7"
services:
  fluentd:
    build:
      context: ./fluentd-green/
      dockerfile: Dockerfile
    image: 587068629442.dkr.ecr.us-gov-west-1.amazonaws.com/core-services:fluentd-green-latest
    ports:
      - "24224:24224"
    deploy:
      mode: global
      restart_policy:
        condition: any

  syslog-ethel-fw-asa-1:
    image: rjocoleman/syslog-cloudwatch-bridge
    env_file:
      - .env
    environment:
      LOG_GROUP_NAME: ethel-fw-asa-1
    ports:
      - "5014:514"
      - "5014:514/udp"
    deploy:
      restart_policy:
        condition: "any"
        delay: 10s
        window: 30s
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
```

.env
```
AWS_REGION=us-gov-west-1
AWS_ACCESS_KEY_ID=E...
AWS_SECRET_ACCESS_KEY=e...
```
container log
```2019/10/14 13:22:28 Starting syslog server on 0.0.0.0:514
2019/10/14 13:22:28 Logging to group: ethel-fw-asa-1
2019/10/14 13:22:29 ResourceNotFoundException: The specified log group does not exist.
        status code: 400, request id: 5dc899a3-44d7-4876-a835-3eaf3f07e476
```
